.TH mycommand 1 September 2024 v1.0 My Command Manual
.SH NAME
mycommand \- short description of the command.
.SH SYNOPSIS
.B mycommand
[\-options] [arguments]
.SH DESCRIPTION
Detailed description of the command and what it does.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.
.TP
.B \-v, \-\-version
Show the version and exit.
.SH EXAMPLES
.B mycommand \-h
Shows the help message.
.B mycommand \-v
Shows the version.
.SH SEE ALSO
.B othercommand(1)

