# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amarnath/Projects/hazmat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amarnath/Projects/hazmat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amarnath/Projects/hazmat/CMakeFiles /home/amarnath/Projects/hazmat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amarnath/Projects/hazmat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hazmat

# Build rule for target.
hazmat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hazmat
.PHONY : hazmat

# fast build rule for target.
hazmat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/build
.PHONY : hazmat/fast

cli/cli.o: cli/cli.cc.o
.PHONY : cli/cli.o

# target to build an object file
cli/cli.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/cli/cli.cc.o
.PHONY : cli/cli.cc.o

cli/cli.i: cli/cli.cc.i
.PHONY : cli/cli.i

# target to preprocess a source file
cli/cli.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/cli/cli.cc.i
.PHONY : cli/cli.cc.i

cli/cli.s: cli/cli.cc.s
.PHONY : cli/cli.s

# target to generate assembly for a file
cli/cli.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/cli/cli.cc.s
.PHONY : cli/cli.cc.s

list/list.o: list/list.cc.o
.PHONY : list/list.o

# target to build an object file
list/list.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/list/list.cc.o
.PHONY : list/list.cc.o

list/list.i: list/list.cc.i
.PHONY : list/list.i

# target to preprocess a source file
list/list.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/list/list.cc.i
.PHONY : list/list.cc.i

list/list.s: list/list.cc.s
.PHONY : list/list.s

# target to generate assembly for a file
list/list.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/list/list.cc.s
.PHONY : list/list.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/main.cc.s
.PHONY : main.cc.s

master/master.o: master/master.cc.o
.PHONY : master/master.o

# target to build an object file
master/master.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/master/master.cc.o
.PHONY : master/master.cc.o

master/master.i: master/master.cc.i
.PHONY : master/master.i

# target to preprocess a source file
master/master.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/master/master.cc.i
.PHONY : master/master.cc.i

master/master.s: master/master.cc.s
.PHONY : master/master.s

# target to generate assembly for a file
master/master.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/master/master.cc.s
.PHONY : master/master.cc.s

password/password.o: password/password.cc.o
.PHONY : password/password.o

# target to build an object file
password/password.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/password/password.cc.o
.PHONY : password/password.cc.o

password/password.i: password/password.cc.i
.PHONY : password/password.i

# target to preprocess a source file
password/password.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/password/password.cc.i
.PHONY : password/password.cc.i

password/password.s: password/password.cc.s
.PHONY : password/password.s

# target to generate assembly for a file
password/password.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hazmat.dir/build.make CMakeFiles/hazmat.dir/password/password.cc.s
.PHONY : password/password.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hazmat"
	@echo "... cli/cli.o"
	@echo "... cli/cli.i"
	@echo "... cli/cli.s"
	@echo "... list/list.o"
	@echo "... list/list.i"
	@echo "... list/list.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... master/master.o"
	@echo "... master/master.i"
	@echo "... master/master.s"
	@echo "... password/password.o"
	@echo "... password/password.i"
	@echo "... password/password.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

